language: php

php:
  - 5.3
  - 5.4

env:
  - MAGE=magento-1-9-1-0
  - MAGE=magento-1-8-1-0
  - MAGE=magento-1-7-0-2
  - MAGE=magento-1-6-2-0
  - MAGE=magento-1-5-1-0

install:
  - cp -f .travis/composer.json composer.json
  - composer install --dev
  - curl https://gordonlesti.com/"$MAGE".tar.gz | tar xz
  - mv $MAGE magento
  - cd magento
  - wget https://raw.githubusercontent.com/colinmollenhour/modman/master/modman
  - chmod +x modman
  - ./modman init
  - cd ..

before_script:
  - mkdir -p build/logs
  - mysql -e 'create database `magento`;'
  - mysql -utravis magento < magento/var/magento.sql
  - mysql -e 'create database `magento_test`;'
  - mysql -utravis magento_test < magento/var/magento_test.sql
  - cd magento
  - ./modman link ./../../Lesti_Fpc
  - ./modman clone https://github.com/EcomDev/EcomDev_PHPUnit.git
  - cd ..

script:
  - php vendor/bin/phpcs --standard=Zend -n app/
  - php vendor/bin/phpmd app/ text codesize,design,unusedcode
  - php vendor/bin/phpcpd app/
  - cd magento && php ../vendor/bin/phpunit --coverage-clover ../build/logs/clover.xml && cd ..

after_script:
  - php vendor/bin/coveralls
