language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

install:
  - composer install --dev --prefer-source
  - curl https://gordonlesti.com/magento-1-9-0-1.tar.gz | tar xz
  - mv magento-1-9-0-1 magento
  - cd magento
  - wget https://raw.githubusercontent.com/colinmollenhour/modman/master/modman
  - chmod +x modman
  - ./modman init
  - cd ..

before_script:
  - mysql -e 'create database `magento-1-9-0-1`;'
  - mysql -utravis magento-1-9-0-1 < magento/magento-1-9-0-1.sql
  - cd magento
  - ./modman link ./../../Lesti_Fpc
  - cd ..

script:
  - php bin/phpcs --standard=Zend -n src/ tests/
  - php bin/phpmd src/,tests/  text codesize,design,unusedcode
  - php bin/phpunit --bootstrap=tests/bootstrap-ci.php
